Repository linode/ansible_linode, pull requests merged in 2024-10, with the labels that each got.

#599 Add GHA job to validate injected documentation
  .github/workflows/docs.yml
Labels: repo-ci-improvement

#600 Correct integration-tests dependency name in CI
  .github/workflows/integration-tests.yml
Labels: bugfix

#601 Account for LUKS headers in instance_config_disk test
  tests/integration/targets/instance_config_disk/tasks/main.yaml
Labels: testing

#614 CI: Notify slack channel on releases
  .github/workflows/release-notify-slack.yml
Labels: repo-ci-improvement
