Repository linode/ansible_linode, pull requests merged in 2024-04, with the labels that each got.

#492 new: Add handling to update logic for unordered lists; use update helper in NB & Instance modules
  docs/modules/nodebalancer.md
  plugins/module_utils/linode_helper.py
  plugins/modules/instance.py
  plugins/modules/nodebalancer.py
  requirements.txt
  tests/integration/targets/nodebalancer_reordered_tags/tasks/main.yaml
Labels: python-sdk-change

#496 fix: Resolve error in `handle_updates` when key is not valid
  plugins/module_utils/linode_helper.py
Labels: bug

#498 Fix plural noun in docs
  README.md
  docs/modules/account_availability_list.md
  docs/modules/vpc_subnet_list.md
  plugins/module_utils/linode_common_list.py
  plugins/modules/account_availability_list.py
  plugins/modules/image_list.py
  plugins/modules/vpc_list.py
  plugins/modules/vpc_subnet_list.py
Labels: documentation

#493 Add `networking_info` attribute to inventory instances
  plugins/inventory/instance.py
  requirements.txt
  tests/integration/targets/instance_inventory/playbooks/test_inventory_filter.yml
Labels: enhancement, python-sdk-change

#499 Add VPC IP List Modules
  README.md
  docs/modules/vpc_ip_list.md
  docs/modules/vpcs_ip_list.md
  plugins/module_utils/doc_fragments/vpc_ip_list.py
  plugins/module_utils/doc_fragments/vpcs_ip_list.py
  plugins/modules/vpc_ip_list.py
  plugins/modules/vpcs_ip_list.py
  tests/integration/targets/vpc_ip_list/tasks/main.yaml
Labels: new-feature

#502 new: update pyenv to use environment name
  .python-version
Labels: repo-ci-improvement
