Repository linode/ansible_linode, pull requests merged in 2024-08, with the labels that each got.

#553 doc: Replace all TODO documentation URLs with TechDocs links
  docs/modules/account_availability_info.md
  docs/modules/account_availability_list.md
  docs/modules/child_account_info.md
  docs/modules/child_account_list.md
  docs/modules/placement_group.md
  docs/modules/placement_group_assign.md
  docs/modules/placement_group_info.md
  docs/modules/placement_group_list.md
  docs/modules/vpc.md
  docs/modules/vpc_info.md
  docs/modules/vpc_ip_list.md
  docs/modules/vpc_list.md
  docs/modules/vpc_subnet.md
  docs/modules/vpc_subnet_info.md
  docs/modules/vpc_subnet_list.md
  docs/modules/vpcs_ip_list.md
  plugins/modules/account_availability_info.py
  plugins/modules/account_availability_list.py
  plugins/modules/child_account_info.py
  plugins/modules/child_account_list.py
  plugins/modules/placement_group.py
  plugins/modules/placement_group_assign.py
  plugins/modules/placement_group_info.py
  plugins/modules/placement_group_list.py
  plugins/modules/vpc.py
  plugins/modules/vpc_info.py
  plugins/modules/vpc_ip_list.py
  plugins/modules/vpc_list.py
  plugins/modules/vpc_subnet.py
  plugins/modules/vpc_subnet_info.py
  plugins/modules/vpc_subnet_list.py
  plugins/modules/vpcs_ip_list.py
Labels: documentation

#554 Add `swap_size` to instance_spec config
  docs/modules/instance.md
  plugins/modules/instance.py
  tests/integration/targets/instance_booted/tasks/main.yaml
Labels: improvement

#556 doc: ssh_key is not updatable
  docs/modules/ssh_key.md
  plugins/modules/ssh_key.py
Labels: documentation

#551 test: Improve E2E test firewall creation and teardown
  Makefile
Labels: testing

#539 new: Support replication in `image` module
  docs/modules/image.md
  plugins/module_utils/doc_fragments/image.py
  plugins/modules/image.py
  tests/integration/targets/image_basic/tasks/main.yaml
Labels: do-not-merge, new-feature

#560 Project: Image Services Gen2
  docs/modules/image.md
  docs/modules/image_info.md
  docs/modules/image_list.md
  plugins/module_utils/doc_fragments/image.py
  plugins/module_utils/doc_fragments/image_list.py
  plugins/modules/image.py
  plugins/modules/image_info.py
  requirements.txt
  tests/integration/targets/image_basic/tasks/main.yaml
Labels: project

#555 update global authors
  docs/modules/account_availability_info.md
  docs/modules/account_availability_list.md
  docs/modules/ip_share.md
  docs/modules/placement_group_info.md
  docs/modules/placement_group_list.md
  docs/modules/vlan_info.md
  docs/modules/vlan_list.md
  plugins/module_utils/linode_docs.py
Labels: documentation

#558 ref: Migrate `profile_info` to use common info module
  docs/modules/profile_info.md
  plugins/module_utils/linode_common_info.py
  plugins/modules/profile_info.py
Labels: improvement

#562 Migrate `account_info` to use common info module
  docs/modules/account_info.md
  plugins/modules/account_info.py
Labels: improvement

#565 Migrate instance_type_list, type_list, and instance_list to use common list module
  README.md
  docs/modules/instance_list.md
  docs/modules/instance_type_list.md
  docs/modules/type_list.md
  plugins/modules/instance_list.py
  plugins/modules/instance_type_list.py
  plugins/modules/type_list.py
Labels: improvement

#563 ref: Migrate domain_record_info to InfoModule base class
  README.md
  docs/modules/domain_record_info.md
  plugins/module_utils/linode_common_info.py
  plugins/modules/domain_record_info.py
  tests/integration/targets/domain_record/tasks/main.yaml
Labels: improvement

#561 ref: Migrate event_list module to ListModule base
  README.md
  docs/modules/event_list.md
  plugins/module_utils/linode_helper.py
  plugins/modules/event_list.py
Labels: improvement

#564 Migrate region_list to use common list module
  README.md
  docs/modules/region_list.md
  plugins/modules/region_list.py
Labels: improvement

#569 fix: Respect existing `zone_file` result structure
  docs/modules/domain.md
  docs/modules/domain_info.md
  plugins/module_utils/doc_fragments/domain.py
  plugins/modules/domain.py
  plugins/modules/domain_info.py
Labels: bugfix

#566 Migrated NodeBalancer-related info and list modules to new framework
  README.md
  docs/modules/nodebalancer_info.md
  docs/modules/nodebalancer_list.md
  docs/modules/nodebalancer_stats.md
  plugins/module_utils/doc_fragments/nodebalancer.py
  plugins/modules/nodebalancer_info.py
  plugins/modules/nodebalancer_list.py
  plugins/modules/nodebalancer_stats.py
  tests/integration/targets/nodebalancer_populated/tasks/main.yaml
  tests/integration/targets/nodebalancer_stats/tasks/main.yaml
Labels: improvement

#574 Bring #572 to `dev` branch
  Makefile
  docs/modules/api_request.md
  docs/modules/ip_info.md
  docs/modules/ip_rdns.md
  docs/modules/ip_share.md
  docs/modules/lke_cluster.md
  docs/modules/lke_cluster_info.md
  docs/modules/nodebalancer_stats.md
  docs/modules/stackscript_list.md
  docs/modules/vpc_ip_list.md
  docs/modules/vpc_subnet.md
  docs/modules/vpc_subnet_info.md
  docs/modules/vpc_subnet_list.md
  docs/modules/vpcs_ip_list.md
  plugins/module_utils/doc_fragments/ip_info.py
  plugins/module_utils/doc_fragments/ip_share.py
  plugins/module_utils/doc_fragments/nodebalancer_stats.py
  plugins/module_utils/doc_fragments/stackscript_list.py
  plugins/module_utils/doc_fragments/vpc_ip_list.py
  plugins/module_utils/doc_fragments/vpc_subnet.py
  plugins/module_utils/doc_fragments/vpc_subnet_list.py
  plugins/module_utils/doc_fragments/vpcs_ip_list.py
  plugins/modules/api_request.py
  plugins/modules/image_info.py
  plugins/modules/instance_type_list.py
  plugins/modules/lke_cluster.py
  plugins/modules/lke_cluster_info.py
  scripts/specdoc_generate.sh
Labels: ignore-for-release

#576 Migrated Token-related info and list modules to new framework
  README.md
  docs/inventory/instance.rst
  docs/modules/token_info.md
  docs/modules/token_list.md
  plugins/modules/token_info.py
  plugins/modules/token_list.py
Labels: improvement

#550 Implemented changes for Linode Disk Encryption
  docs/modules/instance.md
  docs/modules/instance_info.md
  docs/modules/instance_list.md
  docs/modules/lke_cluster.md
  docs/modules/lke_cluster_info.md
  docs/modules/lke_node_pool.md
  plugins/module_utils/doc_fragments/instance.py
  plugins/module_utils/doc_fragments/instance_list.py
  plugins/module_utils/doc_fragments/lke_cluster.py
  plugins/module_utils/doc_fragments/lke_node_pool.py
  plugins/modules/instance.py
  tests/integration/targets/instance_disk_encryption/tasks/main.yaml
  tests/integration/targets/lke_cluster_basic/tasks/main.yaml
  tests/integration/targets/lke_node_pool_basic/tasks/main.yaml
Labels: new-feature

#577 Migrated SSH-Key-related info and list modules to new framework
  README.md
  docs/modules/ssh_key_info.md
  docs/modules/ssh_key_list.md
  plugins/modules/ssh_key_info.py
  plugins/modules/ssh_key_list.py
Labels: improvement

#579 Migrated VLAN-related list module to new framework
  README.md
  docs/modules/vlan_info.md
  docs/modules/vlan_list.md
  plugins/modules/vlan_info.py
  plugins/modules/vlan_list.py
Labels: improvement
