Repository linode/ansible_linode, pull requests merged in 2024-11, with the labels that each got.

#618 test: Allow integration and unit tests to run against EOL or desired python version
  .github/workflows/integration-tests.yml
  .github/workflows/unit-tests.yml
  requirements-dev.txt
Labels: testing

#622 ci: update slack release message
  .github/workflows/integration-tests.yml
  .github/workflows/release-notify-slack.yml
Labels: repo-ci-improvement

#624 Use linode_api4 API error handling logic; remove format_api_error(...) helper
  .github/workflows/docs.yml
  Makefile
  plugins/module_utils/linode_common.py
  plugins/module_utils/linode_helper.py
  requirements.txt
  tests/integration/targets/api_error/tasks/main.yaml
Labels: improvement
