Repository linode/ansible_linode, pull requests merged in 2024-07, with the labels that each got.

#531 new: Support for Multicluster OBJ in object_keys module
  docs/modules/object_keys.md
  plugins/module_utils/doc_fragments/object_keys.py
  plugins/modules/object_keys.py
  requirements.txt
  tests/integration/targets/object_keys_basic/tasks/main.yaml
Labels: new-feature

#546 Add project label
  .github/labels.yml
  .github/release.yml
Labels: repo-ci-improvement

#540 ref: PG affinity_type, is_strict -> placement_group_type, placement_group_policy
  docs/modules/instance.md
  docs/modules/instance_info.md
  docs/modules/placement_group.md
  docs/modules/placement_group_info.md
  docs/modules/placement_group_list.md
  plugins/module_utils/doc_fragments/instance.py
  plugins/module_utils/doc_fragments/placement_group.py
  plugins/module_utils/doc_fragments/placement_group_info.py
  plugins/module_utils/doc_fragments/placement_group_list.py
  plugins/modules/placement_group.py
  requirements.txt
  tests/integration/targets/instance_basic/tasks/main.yaml
  tests/integration/targets/placement_group_assign/tasks/main.yaml
  tests/integration/targets/placement_group_basic/tasks/main.yaml
  tests/integration/targets/placement_group_info/tasks/main.yaml
  tests/integration/targets/placement_group_list/tasks/main.yaml
Labels: improvement, breaking-change

#548 fix: Create SRV domain_record
  docs/modules/domain_record.md
  plugins/module_utils/doc_fragments/domain_record.py
  plugins/modules/domain_record.py
  tests/integration/targets/domain_record/tasks/main.yaml
Labels: bugfix

#552 fix: Fix grants AttributeError; migrate user_info to base InfoModule;
  docs/modules/user_info.md
  plugins/modules/user_info.py
  tests/integration/targets/user_info/tasks/main.yaml
Labels: bugfix
