Repository linode/ansible_linode, pull requests merged in 2024-12, with the labels that each got.

#627 Support `authorized users` field in Instance
  docs/modules/instance.md
  plugins/modules/instance.py
Labels: improvement

#626 doc: Remove Image Services Gen2 LA notice
  docs/inventory/instance.rst
  docs/modules/image.md
  plugins/modules/image.py
Labels: documentation

#629 test: Add smoke test suite and GHA workflow
  .github/workflows/nightly-smoke-tests.yml
  Makefile
  scripts/test_basic_smoke.sh
Labels: testing

#631 test: Update instance_inventory test assertions
  tests/integration/targets/instance_inventory/playbooks/test_inventory_filter.yml
  tests/integration/targets/instance_inventory/playbooks/test_inventory_templatetoken.yml
Labels: testing
