Repository linode/ansible_linode, pull requests merged in 2024-06, with the labels that each got.

#504 CI: replace test execution handler with conditional
  .github/workflows/integration-tests.yml
Labels: repo-ci-improvement

#517 fix: Resolve issues in firewall diff logic
  docs/modules/firewall.md
  plugins/modules/firewall.py
Labels: bugfix

#520 test: Add Calico Inbound and Outbound policies to LKE nodes for E2E
  .github/workflows/integration-tests-pr.yml
  .github/workflows/integration-tests.yml
  scripts/lke-policy.yaml
  scripts/lke_calico_rules_e2e.sh
Labels: testing

#510 new: Add module to manage placement group assignment
  README.md
  docs/modules/placement_group_assign.md
  plugins/module_utils/doc_fragments/placement_group_assign.py
  plugins/modules/placement_group_assign.py
  tests/integration/targets/placement_group_assign/tasks/main.yaml
Labels: new-feature

#523 doc: Add disclaimer for Placement Group LA to documentation
  docs/modules/placement_group.md
  docs/modules/placement_group_assign.md
  plugins/modules/placement_group.py
  plugins/modules/placement_group_assign.py
Labels: documentation

#519 new: Add support for LKE cluster control plane ACLs
  docs/modules/lke_cluster.md
  docs/modules/lke_cluster_info.md
  plugins/module_utils/doc_fragments/lke_cluster.py
  plugins/module_utils/linode_lke_shared.py
  plugins/modules/lke_cluster.py
  plugins/modules/lke_cluster_info.py
  tests/integration/targets/lke_cluster_acl/tasks/main.yaml
Labels: new-feature

#524 project: VM Placement
  README.md
  docs/modules/instance.md
  docs/modules/instance_info.md
  docs/modules/placement_group.md
  docs/modules/placement_group_assign.md
  docs/modules/placement_group_info.md
  docs/modules/placement_group_list.md
  plugins/module_utils/doc_fragments/instance.py
  plugins/module_utils/doc_fragments/placement_group.py
  plugins/module_utils/doc_fragments/placement_group_assign.py
  plugins/module_utils/doc_fragments/placement_group_info.py
  plugins/module_utils/doc_fragments/placement_group_list.py
  plugins/module_utils/linode_common.py
  plugins/modules/instance.py
  plugins/modules/placement_group.py
  plugins/modules/placement_group_assign.py
  plugins/modules/placement_group_info.py
  plugins/modules/placement_group_list.py
  requirements.txt
  tests/integration/targets/instance_basic/tasks/main.yaml
  tests/integration/targets/placement_group_assign/tasks/main.yaml
  tests/integration/targets/placement_group_basic/tasks/main.yaml
  tests/integration/targets/placement_group_info/tasks/main.yaml
  tests/integration/targets/placement_group_list/tasks/main.yaml
Labels: new-feature

#526 doc: Add deprecation notice to OBJ cluster-related modules & fields
  README.md
  docs/modules/object_cluster_info.md
  docs/modules/object_cluster_list.md
  docs/modules/object_keys.md
  plugins/modules/object_cluster_info.py
  plugins/modules/object_cluster_list.py
  plugins/modules/object_keys.py
Labels: documentation, do-not-merge
