Repository linode/ansible_linode, pull requests merged in 2024-09, with the labels that each got.

#568 Migrated Firewall-related info and list modules to new framework
  docs/modules/firewall_info.md
  docs/modules/firewall_list.md
  plugins/modules/firewall_info.py
  plugins/modules/firewall_list.py
Labels: improvement

#583 Release v0.30.1
  README.md
  docs/inventory/instance.rst
  docs/modules/firewall_info.md
  docs/modules/firewall_list.md
  docs/modules/ssh_key_info.md
  docs/modules/ssh_key_list.md
  docs/modules/stackscript_list.md
  docs/modules/token_info.md
  docs/modules/token_list.md
  docs/modules/user_list.md
  docs/modules/vlan_info.md
  docs/modules/vlan_list.md
  plugins/modules/firewall_info.py
  plugins/modules/firewall_list.py
  plugins/modules/ssh_key_info.py
  plugins/modules/ssh_key_list.py
  plugins/modules/stackscript_list.py
  plugins/modules/token_info.py
  plugins/modules/token_list.py
  plugins/modules/user_list.py
  plugins/modules/vlan_info.py
  plugins/modules/vlan_list.py
  template/README.template.md
Labels: ignore-for-release

#575 ref: Migrate object_cluster_list module to ListModule base class; add deprecation support to ListModule and InfoModule
  README.md
  docs/modules/instance_type_list.md
  docs/modules/object_cluster_list.md
  plugins/module_utils/linode_common_info.py
  plugins/module_utils/linode_common_list.py
  plugins/modules/instance_type_list.py
  plugins/modules/object_cluster_list.py
  tests/integration/targets/object_cluster_list/tasks/main.yaml
Labels: improvement

#580 new: Support LKE node pool labels and taints
  docs/modules/lke_cluster.md
  docs/modules/lke_node_pool.md
  plugins/module_utils/linode_helper.py
  plugins/modules/lke_cluster.py
  plugins/modules/lke_node_pool.py
  requirements.txt
  tests/integration/targets/lke_cluster_basic/tasks/main.yaml
  tests/integration/targets/lke_node_pool_basic/tasks/main.yaml
Labels: new-feature

#582 Implemented changes for Linode Disk Encryption (re-merge)
  docs/modules/instance.md
  docs/modules/instance_info.md
  docs/modules/instance_list.md
  docs/modules/lke_cluster.md
  docs/modules/lke_cluster_info.md
  docs/modules/lke_node_pool.md
  plugins/module_utils/doc_fragments/instance.py
  plugins/module_utils/doc_fragments/instance_list.py
  plugins/module_utils/doc_fragments/lke_cluster.py
  plugins/module_utils/doc_fragments/lke_node_pool.py
  plugins/modules/instance.py
  tests/integration/targets/instance_disk_encryption/tasks/main.yaml
  tests/integration/targets/lke_cluster_basic/tasks/main.yaml
  tests/integration/targets/lke_node_pool_basic/tasks/main.yaml
Labels: new-feature

#589 Refactor image replication test cases
  plugins/module_utils/linode_common.py
  plugins/module_utils/linode_common_info.py
  plugins/module_utils/linode_common_list.py
  tests/integration/targets/image_basic/tasks/main.yaml
Labels: testing
