Repository linode/ansible_linode, pull requests merged in 2025-05, with the labels that each got.

#668 Cleanup unnecessary steps in release workflow
  .github/workflows/release.yml
Labels: repo-ci-improvement

#659 Add DBaaS Suspend and Resume
  docs/modules/database_mysql_v2.md
  docs/modules/database_postgresql_v2.md
  plugins/modules/database_mysql_v2.py
  plugins/modules/database_postgresql_v2.py
  tests/integration/targets/database_mysql_v2_basic/tasks/main.yaml
  tests/integration/targets/database_postgresql_v2_basic/tasks/main.yaml
Labels: improvement

#671 Support Object Storage Quota modules
  README.md
  docs/modules/object_storage_quota_info.md
  docs/modules/object_storage_quota_list.md
  plugins/module_utils/doc_fragments/object_storage_quota_info.py
  plugins/module_utils/doc_fragments/object_storage_quota_list.py
  plugins/module_utils/linode_common_list.py
  plugins/modules/object_storage_quota_info.py
  plugins/modules/object_storage_quota_list.py
  tests/integration/targets/object_storage_quota_info/tasks/main.yaml
  tests/integration/targets/object_storage_quota_list/tasks/main.yaml
Labels: new-feature

#670 Configurable DB Parameters: Implementation
  README.md
  docs/modules/database_config_info.md
  docs/modules/database_mysql_v2.md
  docs/modules/database_postgresql_v2.md
  plugins/module_utils/doc_fragments/database_config_info.py
  plugins/module_utils/doc_fragments/database_mysql_v2.py
  plugins/module_utils/doc_fragments/database_postgresql_v2.py
  plugins/module_utils/linode_helper.py
  plugins/modules/database_config_info.py
  plugins/modules/database_mysql_v2.py
  plugins/modules/database_postgresql_v2.py
  requirements.txt
  tests/integration/targets/database_config_info/tasks/main.yaml
  tests/integration/targets/database_mysql_v2_engine_config/tasks/main.yaml
  tests/integration/targets/database_postgresql_v2_engine_config/tasks/main.yaml
Labels: new-feature

#678 Project: Configurable DB Params
  README.md
  docs/modules/database_config_info.md
  docs/modules/database_mysql_v2.md
  docs/modules/database_postgresql_v2.md
  plugins/module_utils/doc_fragments/database_config_info.py
  plugins/module_utils/doc_fragments/database_mysql_v2.py
  plugins/module_utils/doc_fragments/database_postgresql_v2.py
  plugins/module_utils/linode_helper.py
  plugins/modules/database_config_info.py
  plugins/modules/database_mysql_v2.py
  plugins/modules/database_postgresql_v2.py
  requirements.txt
  tests/integration/targets/database_config_info/tasks/main.yaml
  tests/integration/targets/database_mysql_v2_engine_config/tasks/main.yaml
  tests/integration/targets/database_postgresql_v2_engine_config/tasks/main.yaml
Labels: project

#680 Respond to `parse_linode_types(...)` JSONObject serialization in instance module
  plugins/modules/instance.py
Labels: bugfix

#681 Firewall settings modules
  README.md
  docs/modules/firewall_settings.md
  docs/modules/firewall_settings_info.md
  plugins/module_utils/doc_fragments/firewall_settings.py
  plugins/module_utils/doc_fragments/firewall_settings_info.py
  plugins/modules/firewall_settings.py
  plugins/modules/firewall_settings_info.py
  tests/integration/targets/firewall_settings/tasks/main.yaml
Labels: new-feature
