Repository linode/ansible_linode, pull requests merged in 2025-02, with the labels that each got.

#638 Added support for NodeBalancers UDP
  .github/workflows/docs.yml
  docs/inventory/instance.rst
  docs/modules/nodebalancer.md
  plugins/module_utils/linode_common.py
  plugins/modules/nodebalancer.py
  requirements.txt
  tests/integration/targets/nodebalancer_udp/tasks/main.yaml
Labels: do-not-merge, new-feature, breaking-change

#644 Format using up-to-date dev dependencies
  docs/inventory/instance.rst
  plugins/module_utils/linode_common.py
Labels: bugfix

#646 test: Add empty `addresses` when disabling ACL
  tests/integration/targets/lke_cluster_acl/tasks/main.yaml
Labels: testing

#643 Release v0.34.1
  .github/workflows/docs.yml
  .github/workflows/integration-tests-pr.yml
  .github/workflows/integration-tests.yml
  .github/workflows/labeler.yml
  .github/workflows/nightly-smoke-tests.yml
  .github/workflows/unit-tests.yml
  Makefile
  docs/inventory/instance.rst
  plugins/module_utils/linode_common.py
  requirements.txt
  tests/integration/targets/lke_cluster_acl/tasks/main.yaml
Labels: ignore-for-release

#647 Add support for Object Storage Gen. 2
  README.md
  docs/modules/object_storage_endpoint_list.md
  plugins/module_utils/doc_fragments/object_storage_endpoint_list.py
  plugins/modules/object_storage_endpoint_list.py
  tests/integration/targets/object_storage_endpoint_list/tasks/main.yaml
Labels: new-feature

#645 Implement linode.cloud.database_mysql_v2 module
  README.md
  docs/modules/database_mysql_v2.md
  plugins/module_utils/doc_fragments/database_mysql_v2.py
  plugins/module_utils/linode_database_shared.py
  plugins/module_utils/linode_helper.py
  plugins/modules/database_mysql_v2.py
  tests/integration/targets/database_mysql_v2_basic/tasks/main.yaml
  tests/integration/targets/database_mysql_v2_complex/tasks/main.yaml
Labels: new-feature

#651 Remove LKE ACL LA notices
  docs/modules/lke_cluster.md
  plugins/modules/lke_cluster.py
Labels: documentation
