Repository linode/ansible_linode, pull requests merged in 2025-08, with the labels that each got.

#696 Release v0.41.0
  .github/workflows/integration-tests-pr.yml
  docs/modules/instance.md
  plugins/module_utils/doc_fragments/instance.py
  plugins/modules/instance.py
  tests/integration/targets/database_config_info/tasks/main.yaml
  tests/integration/targets/instance_basic/tasks/main.yaml
  tests/integration/targets/instance_interfaces/tasks/main.yaml
Labels: ignore-for-release

#701 project: Host / VM Maintenance Policy
  README.md
  docs/modules/account_settings.md
  docs/modules/instance.md
  docs/modules/instance_info.md
  docs/modules/instance_list.md
  docs/modules/maintenance_policy_list.md
  plugins/module_utils/doc_fragments/account_settings.py
  plugins/module_utils/doc_fragments/instance.py
  plugins/module_utils/doc_fragments/instance_list.py
  plugins/module_utils/doc_fragments/maintenance_policy_list.py
  plugins/modules/account_settings.py
  plugins/modules/instance.py
  plugins/modules/instance_list.py
  plugins/modules/maintenance_policy_list.py
  requirements.txt
  tests/integration/targets/account_settings/tasks/main.yaml
  tests/integration/targets/instance_basic/tasks/main.yaml
  tests/integration/targets/maintenance_policy_list/tasks/main.yaml
Labels: project

#702 Require Maintenance Policy capability in instance_basic test
  tests/integration/targets/instance_basic/tasks/main.yaml
Labels: bugfix
